# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'TaboolaSDKExampleSwift' do
  use_frameworks!
  
  pod 'TaboolaSDK', '3.4.0'

  end